name: Application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: PNPM
      run: |
        corepack enable

    - name: Build
      run: |
        pnpm i
        pnpm build

  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: PNPM
      run: |
        corepack enable

    - name: Tests
      run: |
        pnpm i
        pnpm test

    - name: CodeCov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/cobertura-coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: PNPM
      run: |
        corepack enable

    - name: Lint
      run: |
        pnpm i
        pnpm lint
