name: Application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Yarn Berry
      run: |
        corepack enable
        yarn set version stable

    - name: Build
      run: |
        yarn
        yarn workspace @izui/scripts build
        yarn build

  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Yarn Berry
      run: |
        corepack enable
        yarn set version stable

    - name: Tests
      run: |
        yarn
        yarn test

    - name: CodeCov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/cobertura-coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Yarn Berry
      run: |
        corepack enable
        yarn set version stable

    - name: Lint
      run: |
        yarn
        yarn lint
