name: Application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        yarn set version latest
        yarn
        yarn build

    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: .

  tests:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Artifact
      uses: actions/download-artifact@v2
      with:
        name: artifact
        path: .

    - name: Tests
      run: |
        yarn test

    - name: CodeCov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/cobertura-coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true

  lint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Artifact
      uses: actions/download-artifact@v2
      with:
        name: artifact
        path: .

    - name: Lint
      run: |
        yarn lint
